const subCategory=[
   { id : 1, label : "T-shirts", value : "T-shirts"},
   { id : 2, label : "Shirts", value : "Shirts"},
   { id : 3, label : "Hoodies & Sweatshirts", value : "Hoodies & Sweatshirts"},
   { id : 4, label : "Blazers & Coats", value : "Blazers & Coats"},
   { id : 5, label : "Jackets", value : "Jackets"},
   { id : 6, label : "Sweaters", value : "Sweaters"},
   { id : 7, label : "Tank Tops", value : "Tank Tops"},
   { id : 8, label : "Crop Tops", value : "Crop Tops"},
   { id : 8, label : "Tunics", value : "Tunics"},
   { id : 10, label : "Jeans", value : "Jeans"},
   { id : 11, label : "Shorts", value : "Shorts"},
   { id : 12, label : "Joggers & Track Pants", value : "Joggers & Track Pants"},
   { id : 13, label : "Leggings", value : "Leggings"},
   { id : 14, label : "Skirts", value : "Skirts"},
   { id : 15, label : "Sarees", value : "Sarees"},
   { id : 16, label : "Kurtas & Kurtis", value : "Kurtas & Kurtis"},
   { id : 17, label : "Salwar Kameez", value : "Salwar Kameez"},
   { id : 18, label : "Lehengas", value : "Lehengas"},
   { id : 19, label : "Sherwanis", value : "Sherwanis"},
   { id : 20, label : "Dhoti & Mundu", value : "Dhoti & Mundu"},
   { id : 21, label : "Anarkali Suits", value : "Anarkali Suits"},
   { id : 22, label : "Undergarments (Briefs, Boxers, Panties, Bras)", value : "Undergarments (Briefs, Boxers, Panties, Bras)"},
   { id : 23, label : "Nightwear & Pajamas", value : "Nightwear & Pajamas"},
   { id : 24, label : "Thermals", value : "Thermals"},
   { id : 25, label : "Camisoles & Slips", value : "Camisoles & Slips"},
   { id : 26, label : "Gym & Workout Clothes", value : "Gym & Workout Clothes"},
   { id : 27, label : "Yoga Pants", value : "Yoga Pants"},
   { id : 28, label : "Compression Wear", value : "Compression Wear"},
   { id : 29, label : "Swimwear", value : "Swimwear"},
   { id : 30, label : "Sports Jerseys", value : "Sports Jerseys"},
   { id : 31, label : "Overcoats", value : "Overcoats"},
   { id : 32, label : "Woolen Sweaters", value : "Woolen Sweaters"},
   { id : 33, label : "Scarves & Mufflers", value : "Scarves & Mufflers"},
   { id : 34, label : "Thermal Wear", value : "Thermal Wear"},
   { id : 35, label : "Raincoats", value : "Raincoats"},
   { id : 36, label : "Suits & Blazers", value : "Suits & Blazers"},
   { id : 37, label : "Formal Shirts & Trousers", value : "Formal Shirts & Trousers"},
   { id : 38, label : "Pencil Skirts", value : "Pencil Skirts"},
   { id : 39, label : "Business Dresses", value : "Business Dresses"},
   { id : 40, label : "Cocktail Dresses", value : "Cocktail Dresses"},
   { id : 41, label : "Gowns", value : "Gowns"},
   { id : 42, label : "Tuxedos", value : "Tuxedos"},
   { id : 43, label : "Wedding Attire", value : "Wedding Attire"},
   
]


export default subCategory